version: 2

models:
  - name: player_performance
    columns:
      - name: player_id
        tests:
          - unique
          - not_null

      - name: career_kda
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

  - name: tournament_standings
    columns:
      - name: team_id
        tests:
          - unique

      - name: total_wins
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

  - name: prize_earnings
    columns:
      - name: id
        tests:
          - unique